DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS item;

CREATE TABLE user (
	userId INT UNSIGNED AUTO_INCREMENT NOT NULL,
	email VARCHAR(128),
	PRIMARY KEY(userId)
)

CREATE TABLE item (
	itemId INT UNSIGNED AUTO_INCREMENT NOT NULL,
	userId INT UNSIGNED NOT NULL,
	itemDescription VARCHAR(2000) NOT NULL,
	images VARCHAR (64),
	email VARCHAR (128) NOT NULL,
	price INT UNSIGNED,
	location VARCHAR (64) NOT NULL,
	PRIMARY KEY(itemId),
	FOREIGN KEY(userId) REFERENCES user(userId)
);


DESCRIBE item;
SELECT * FROM item;
SELECT * FROM user;